---
# Configuration Template for Lichess Twitch Bot
twitch:
  username: <TWITCH BOT USERNAME>
  owner: <TWITCH BOT OWNER>
  client_id: <TWITCH CLIENT ID>
  token: <TWITCH TOKEN>
lichess:
  token: <LICHESS TOKEN>
  url: https://lichess.org/
